//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("KTModel", "fk_Answers_Questionid", "Question", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(KT.DB.Question), "Answer", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(KT.DB.Answer), true)]
[assembly: EdmRelationshipAttribute("KTModel", "fk_Categories_users", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(KT.DB.User), "Category", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(KT.DB.Category), true)]
[assembly: EdmRelationshipAttribute("KTModel", "fk_GeneratedQuestions_GeneratedTestId", "GeneratedTest", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(KT.DB.GeneratedTest), "GeneratedQuestion", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(KT.DB.GeneratedQuestion), true)]
[assembly: EdmRelationshipAttribute("KTModel", "fk_GeneratedQuestions_QuestionId", "Question", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(KT.DB.Question), "GeneratedQuestion", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(KT.DB.GeneratedQuestion), true)]
[assembly: EdmRelationshipAttribute("KTModel", "fk_GeneratedTests_Username", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(KT.DB.User), "GeneratedTest", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(KT.DB.GeneratedTest), true)]
[assembly: EdmRelationshipAttribute("KTModel", "fk_Questions_SubcategoryId", "Subcategory", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(KT.DB.Subcategory), "Question", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(KT.DB.Question), true)]
[assembly: EdmRelationshipAttribute("KTModel", "fk_GeneratedAnswers_Answers", "Answer", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(KT.DB.Answer), "GeneratedAnswer", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(KT.DB.GeneratedAnswer), true)]
[assembly: EdmRelationshipAttribute("KTModel", "fk_GeneratedAnswers_GeneratedQuestionId", "GeneratedQuestion", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(KT.DB.GeneratedQuestion), "GeneratedAnswer", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(KT.DB.GeneratedAnswer), true)]
[assembly: EdmRelationshipAttribute("KTModel", "fk_GeneratedTests_TestId", "Test", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(KT.DB.Test), "GeneratedTest", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(KT.DB.GeneratedTest), true)]
[assembly: EdmRelationshipAttribute("KTModel", "fk_tests_SubcategoryId", "Subcategory", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(KT.DB.Subcategory), "Test", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(KT.DB.Test), true)]
[assembly: EdmRelationshipAttribute("KTModel", "Subscriptions", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(KT.DB.User), "Test", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(KT.DB.Test))]

#endregion

namespace KT.DB
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class KTEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new KTEntities object using the connection string found in the 'KTEntities' section of the application configuration file.
        /// </summary>
        public KTEntities() : base("name=KTEntities", "KTEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new KTEntities object.
        /// </summary>
        public KTEntities(string connectionString) : base(connectionString, "KTEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new KTEntities object.
        /// </summary>
        public KTEntities(EntityConnection connection) : base(connection, "KTEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Answer> Answers
        {
            get
            {
                if ((_Answers == null))
                {
                    _Answers = base.CreateObjectSet<Answer>("Answers");
                }
                return _Answers;
            }
        }
        private ObjectSet<Answer> _Answers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Category> Categories
        {
            get
            {
                if ((_Categories == null))
                {
                    _Categories = base.CreateObjectSet<Category>("Categories");
                }
                return _Categories;
            }
        }
        private ObjectSet<Category> _Categories;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<GeneratedQuestion> GeneratedQuestions
        {
            get
            {
                if ((_GeneratedQuestions == null))
                {
                    _GeneratedQuestions = base.CreateObjectSet<GeneratedQuestion>("GeneratedQuestions");
                }
                return _GeneratedQuestions;
            }
        }
        private ObjectSet<GeneratedQuestion> _GeneratedQuestions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<GeneratedTest> GeneratedTests
        {
            get
            {
                if ((_GeneratedTests == null))
                {
                    _GeneratedTests = base.CreateObjectSet<GeneratedTest>("GeneratedTests");
                }
                return _GeneratedTests;
            }
        }
        private ObjectSet<GeneratedTest> _GeneratedTests;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Question> Questions
        {
            get
            {
                if ((_Questions == null))
                {
                    _Questions = base.CreateObjectSet<Question>("Questions");
                }
                return _Questions;
            }
        }
        private ObjectSet<Question> _Questions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Subcategory> Subcategories
        {
            get
            {
                if ((_Subcategories == null))
                {
                    _Subcategories = base.CreateObjectSet<Subcategory>("Subcategories");
                }
                return _Subcategories;
            }
        }
        private ObjectSet<Subcategory> _Subcategories;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<GeneratedAnswer> GeneratedAnswers
        {
            get
            {
                if ((_GeneratedAnswers == null))
                {
                    _GeneratedAnswers = base.CreateObjectSet<GeneratedAnswer>("GeneratedAnswers");
                }
                return _GeneratedAnswers;
            }
        }
        private ObjectSet<GeneratedAnswer> _GeneratedAnswers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Test> Tests
        {
            get
            {
                if ((_Tests == null))
                {
                    _Tests = base.CreateObjectSet<Test>("Tests");
                }
                return _Tests;
            }
        }
        private ObjectSet<Test> _Tests;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Answers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAnswers(Answer answer)
        {
            base.AddObject("Answers", answer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Categories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCategories(Category category)
        {
            base.AddObject("Categories", category);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the GeneratedQuestions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGeneratedQuestions(GeneratedQuestion generatedQuestion)
        {
            base.AddObject("GeneratedQuestions", generatedQuestion);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the GeneratedTests EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGeneratedTests(GeneratedTest generatedTest)
        {
            base.AddObject("GeneratedTests", generatedTest);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Questions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToQuestions(Question question)
        {
            base.AddObject("Questions", question);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Subcategories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSubcategories(Subcategory subcategory)
        {
            base.AddObject("Subcategories", subcategory);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the GeneratedAnswers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGeneratedAnswers(GeneratedAnswer generatedAnswer)
        {
            base.AddObject("GeneratedAnswers", generatedAnswer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Tests EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTests(Test test)
        {
            base.AddObject("Tests", test);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KTModel", Name="Answer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Answer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Answer object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="text">Initial value of the Text property.</param>
        /// <param name="isCorrect">Initial value of the IsCorrect property.</param>
        /// <param name="questionId">Initial value of the QuestionId property.</param>
        public static Answer CreateAnswer(global::System.Guid id, global::System.String text, global::System.Boolean isCorrect, global::System.Guid questionId)
        {
            Answer answer = new Answer();
            answer.Id = id;
            answer.Text = text;
            answer.IsCorrect = isCorrect;
            answer.QuestionId = questionId;
            return answer;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Text
        {
            get
            {
                return _Text;
            }
            set
            {
                OnTextChanging(value);
                ReportPropertyChanging("Text");
                _Text = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Text");
                OnTextChanged();
            }
        }
        private global::System.String _Text;
        partial void OnTextChanging(global::System.String value);
        partial void OnTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsCorrect
        {
            get
            {
                return _IsCorrect;
            }
            set
            {
                OnIsCorrectChanging(value);
                ReportPropertyChanging("IsCorrect");
                _IsCorrect = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsCorrect");
                OnIsCorrectChanged();
            }
        }
        private global::System.Boolean _IsCorrect;
        partial void OnIsCorrectChanging(global::System.Boolean value);
        partial void OnIsCorrectChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid QuestionId
        {
            get
            {
                return _QuestionId;
            }
            set
            {
                OnQuestionIdChanging(value);
                ReportPropertyChanging("QuestionId");
                _QuestionId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("QuestionId");
                OnQuestionIdChanged();
            }
        }
        private global::System.Guid _QuestionId;
        partial void OnQuestionIdChanging(global::System.Guid value);
        partial void OnQuestionIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KTModel", "fk_Answers_Questionid", "Question")]
        public Question Question
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Question>("KTModel.fk_Answers_Questionid", "Question").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Question>("KTModel.fk_Answers_Questionid", "Question").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Question> QuestionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Question>("KTModel.fk_Answers_Questionid", "Question");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Question>("KTModel.fk_Answers_Questionid", "Question", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KTModel", "fk_GeneratedAnswers_Answers", "GeneratedAnswer")]
        public EntityCollection<GeneratedAnswer> GeneratedAnswers
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<GeneratedAnswer>("KTModel.fk_GeneratedAnswers_Answers", "GeneratedAnswer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<GeneratedAnswer>("KTModel.fk_GeneratedAnswers_Answers", "GeneratedAnswer", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KTModel", Name="Category")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Category : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Category object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="createdByUser">Initial value of the CreatedByUser property.</param>
        public static Category CreateCategory(global::System.Guid id, global::System.String name, global::System.String createdByUser)
        {
            Category category = new Category();
            category.Id = id;
            category.Name = name;
            category.CreatedByUser = createdByUser;
            return category;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CreatedByUser
        {
            get
            {
                return _CreatedByUser;
            }
            set
            {
                OnCreatedByUserChanging(value);
                ReportPropertyChanging("CreatedByUser");
                _CreatedByUser = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CreatedByUser");
                OnCreatedByUserChanged();
            }
        }
        private global::System.String _CreatedByUser;
        partial void OnCreatedByUserChanging(global::System.String value);
        partial void OnCreatedByUserChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KTModel", "fk_Categories_users", "User")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("KTModel.fk_Categories_users", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("KTModel.fk_Categories_users", "User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("KTModel.fk_Categories_users", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("KTModel.fk_Categories_users", "User", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KTModel", Name="GeneratedAnswer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class GeneratedAnswer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GeneratedAnswer object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="generatedQuestionId">Initial value of the GeneratedQuestionId property.</param>
        /// <param name="answerId">Initial value of the AnswerId property.</param>
        /// <param name="isSelected">Initial value of the IsSelected property.</param>
        public static GeneratedAnswer CreateGeneratedAnswer(global::System.Guid id, global::System.Guid generatedQuestionId, global::System.Guid answerId, global::System.Boolean isSelected)
        {
            GeneratedAnswer generatedAnswer = new GeneratedAnswer();
            generatedAnswer.Id = id;
            generatedAnswer.GeneratedQuestionId = generatedQuestionId;
            generatedAnswer.AnswerId = answerId;
            generatedAnswer.IsSelected = isSelected;
            return generatedAnswer;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid GeneratedQuestionId
        {
            get
            {
                return _GeneratedQuestionId;
            }
            set
            {
                OnGeneratedQuestionIdChanging(value);
                ReportPropertyChanging("GeneratedQuestionId");
                _GeneratedQuestionId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GeneratedQuestionId");
                OnGeneratedQuestionIdChanged();
            }
        }
        private global::System.Guid _GeneratedQuestionId;
        partial void OnGeneratedQuestionIdChanging(global::System.Guid value);
        partial void OnGeneratedQuestionIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid AnswerId
        {
            get
            {
                return _AnswerId;
            }
            set
            {
                OnAnswerIdChanging(value);
                ReportPropertyChanging("AnswerId");
                _AnswerId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AnswerId");
                OnAnswerIdChanged();
            }
        }
        private global::System.Guid _AnswerId;
        partial void OnAnswerIdChanging(global::System.Guid value);
        partial void OnAnswerIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsSelected
        {
            get
            {
                return _IsSelected;
            }
            set
            {
                OnIsSelectedChanging(value);
                ReportPropertyChanging("IsSelected");
                _IsSelected = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsSelected");
                OnIsSelectedChanged();
            }
        }
        private global::System.Boolean _IsSelected;
        partial void OnIsSelectedChanging(global::System.Boolean value);
        partial void OnIsSelectedChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KTModel", "fk_GeneratedAnswers_Answers", "Answer")]
        public Answer Answer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Answer>("KTModel.fk_GeneratedAnswers_Answers", "Answer").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Answer>("KTModel.fk_GeneratedAnswers_Answers", "Answer").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Answer> AnswerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Answer>("KTModel.fk_GeneratedAnswers_Answers", "Answer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Answer>("KTModel.fk_GeneratedAnswers_Answers", "Answer", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KTModel", "fk_GeneratedAnswers_GeneratedQuestionId", "GeneratedQuestion")]
        public GeneratedQuestion GeneratedQuestion
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GeneratedQuestion>("KTModel.fk_GeneratedAnswers_GeneratedQuestionId", "GeneratedQuestion").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GeneratedQuestion>("KTModel.fk_GeneratedAnswers_GeneratedQuestionId", "GeneratedQuestion").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<GeneratedQuestion> GeneratedQuestionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GeneratedQuestion>("KTModel.fk_GeneratedAnswers_GeneratedQuestionId", "GeneratedQuestion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<GeneratedQuestion>("KTModel.fk_GeneratedAnswers_GeneratedQuestionId", "GeneratedQuestion", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KTModel", Name="GeneratedQuestion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class GeneratedQuestion : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GeneratedQuestion object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="generatedTestId">Initial value of the GeneratedTestId property.</param>
        /// <param name="questionId">Initial value of the QuestionId property.</param>
        /// <param name="argumentText">Initial value of the ArgumentText property.</param>
        public static GeneratedQuestion CreateGeneratedQuestion(global::System.Guid id, global::System.Guid generatedTestId, global::System.Guid questionId, global::System.String argumentText)
        {
            GeneratedQuestion generatedQuestion = new GeneratedQuestion();
            generatedQuestion.Id = id;
            generatedQuestion.GeneratedTestId = generatedTestId;
            generatedQuestion.QuestionId = questionId;
            generatedQuestion.ArgumentText = argumentText;
            return generatedQuestion;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid GeneratedTestId
        {
            get
            {
                return _GeneratedTestId;
            }
            set
            {
                OnGeneratedTestIdChanging(value);
                ReportPropertyChanging("GeneratedTestId");
                _GeneratedTestId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GeneratedTestId");
                OnGeneratedTestIdChanged();
            }
        }
        private global::System.Guid _GeneratedTestId;
        partial void OnGeneratedTestIdChanging(global::System.Guid value);
        partial void OnGeneratedTestIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid QuestionId
        {
            get
            {
                return _QuestionId;
            }
            set
            {
                OnQuestionIdChanging(value);
                ReportPropertyChanging("QuestionId");
                _QuestionId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("QuestionId");
                OnQuestionIdChanged();
            }
        }
        private global::System.Guid _QuestionId;
        partial void OnQuestionIdChanging(global::System.Guid value);
        partial void OnQuestionIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ArgumentText
        {
            get
            {
                return _ArgumentText;
            }
            set
            {
                OnArgumentTextChanging(value);
                ReportPropertyChanging("ArgumentText");
                _ArgumentText = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ArgumentText");
                OnArgumentTextChanged();
            }
        }
        private global::System.String _ArgumentText;
        partial void OnArgumentTextChanging(global::System.String value);
        partial void OnArgumentTextChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KTModel", "fk_GeneratedQuestions_GeneratedTestId", "GeneratedTest")]
        public GeneratedTest GeneratedTest
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GeneratedTest>("KTModel.fk_GeneratedQuestions_GeneratedTestId", "GeneratedTest").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GeneratedTest>("KTModel.fk_GeneratedQuestions_GeneratedTestId", "GeneratedTest").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<GeneratedTest> GeneratedTestReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GeneratedTest>("KTModel.fk_GeneratedQuestions_GeneratedTestId", "GeneratedTest");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<GeneratedTest>("KTModel.fk_GeneratedQuestions_GeneratedTestId", "GeneratedTest", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KTModel", "fk_GeneratedQuestions_QuestionId", "Question")]
        public Question Question
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Question>("KTModel.fk_GeneratedQuestions_QuestionId", "Question").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Question>("KTModel.fk_GeneratedQuestions_QuestionId", "Question").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Question> QuestionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Question>("KTModel.fk_GeneratedQuestions_QuestionId", "Question");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Question>("KTModel.fk_GeneratedQuestions_QuestionId", "Question", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KTModel", "fk_GeneratedAnswers_GeneratedQuestionId", "GeneratedAnswer")]
        public EntityCollection<GeneratedAnswer> GeneratedAnswers
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<GeneratedAnswer>("KTModel.fk_GeneratedAnswers_GeneratedQuestionId", "GeneratedAnswer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<GeneratedAnswer>("KTModel.fk_GeneratedAnswers_GeneratedQuestionId", "GeneratedAnswer", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KTModel", Name="GeneratedTest")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class GeneratedTest : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GeneratedTest object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="username">Initial value of the Username property.</param>
        /// <param name="testId">Initial value of the TestId property.</param>
        /// <param name="isFinished">Initial value of the IsFinished property.</param>
        /// <param name="isVerified">Initial value of the IsVerified property.</param>
        /// <param name="maxScore">Initial value of the MaxScore property.</param>
        /// <param name="score">Initial value of the Score property.</param>
        public static GeneratedTest CreateGeneratedTest(global::System.Guid id, global::System.String username, global::System.Guid testId, global::System.Boolean isFinished, global::System.Boolean isVerified, global::System.Int32 maxScore, global::System.Int32 score)
        {
            GeneratedTest generatedTest = new GeneratedTest();
            generatedTest.Id = id;
            generatedTest.Username = username;
            generatedTest.TestId = testId;
            generatedTest.IsFinished = isFinished;
            generatedTest.IsVerified = isVerified;
            generatedTest.MaxScore = maxScore;
            generatedTest.Score = score;
            return generatedTest;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Username
        {
            get
            {
                return _Username;
            }
            set
            {
                OnUsernameChanging(value);
                ReportPropertyChanging("Username");
                _Username = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Username");
                OnUsernameChanged();
            }
        }
        private global::System.String _Username;
        partial void OnUsernameChanging(global::System.String value);
        partial void OnUsernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid TestId
        {
            get
            {
                return _TestId;
            }
            set
            {
                OnTestIdChanging(value);
                ReportPropertyChanging("TestId");
                _TestId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TestId");
                OnTestIdChanged();
            }
        }
        private global::System.Guid _TestId;
        partial void OnTestIdChanging(global::System.Guid value);
        partial void OnTestIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsFinished
        {
            get
            {
                return _IsFinished;
            }
            set
            {
                OnIsFinishedChanging(value);
                ReportPropertyChanging("IsFinished");
                _IsFinished = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsFinished");
                OnIsFinishedChanged();
            }
        }
        private global::System.Boolean _IsFinished;
        partial void OnIsFinishedChanging(global::System.Boolean value);
        partial void OnIsFinishedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsVerified
        {
            get
            {
                return _IsVerified;
            }
            set
            {
                OnIsVerifiedChanging(value);
                ReportPropertyChanging("IsVerified");
                _IsVerified = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsVerified");
                OnIsVerifiedChanged();
            }
        }
        private global::System.Boolean _IsVerified;
        partial void OnIsVerifiedChanging(global::System.Boolean value);
        partial void OnIsVerifiedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MaxScore
        {
            get
            {
                return _MaxScore;
            }
            set
            {
                OnMaxScoreChanging(value);
                ReportPropertyChanging("MaxScore");
                _MaxScore = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaxScore");
                OnMaxScoreChanged();
            }
        }
        private global::System.Int32 _MaxScore;
        partial void OnMaxScoreChanging(global::System.Int32 value);
        partial void OnMaxScoreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Score
        {
            get
            {
                return _Score;
            }
            set
            {
                OnScoreChanging(value);
                ReportPropertyChanging("Score");
                _Score = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Score");
                OnScoreChanged();
            }
        }
        private global::System.Int32 _Score;
        partial void OnScoreChanging(global::System.Int32 value);
        partial void OnScoreChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KTModel", "fk_GeneratedQuestions_GeneratedTestId", "GeneratedQuestion")]
        public EntityCollection<GeneratedQuestion> GeneratedQuestions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<GeneratedQuestion>("KTModel.fk_GeneratedQuestions_GeneratedTestId", "GeneratedQuestion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<GeneratedQuestion>("KTModel.fk_GeneratedQuestions_GeneratedTestId", "GeneratedQuestion", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KTModel", "fk_GeneratedTests_Username", "User")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("KTModel.fk_GeneratedTests_Username", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("KTModel.fk_GeneratedTests_Username", "User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("KTModel.fk_GeneratedTests_Username", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("KTModel.fk_GeneratedTests_Username", "User", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KTModel", "fk_GeneratedTests_TestId", "Test")]
        public Test Test
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Test>("KTModel.fk_GeneratedTests_TestId", "Test").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Test>("KTModel.fk_GeneratedTests_TestId", "Test").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Test> TestReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Test>("KTModel.fk_GeneratedTests_TestId", "Test");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Test>("KTModel.fk_GeneratedTests_TestId", "Test", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KTModel", Name="Question")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Question : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Question object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="text">Initial value of the Text property.</param>
        /// <param name="correctArgument">Initial value of the CorrectArgument property.</param>
        /// <param name="subcategoryId">Initial value of the SubcategoryId property.</param>
        /// <param name="multipleAnswer">Initial value of the MultipleAnswer property.</param>
        public static Question CreateQuestion(global::System.Guid id, global::System.String text, global::System.String correctArgument, global::System.Guid subcategoryId, global::System.Boolean multipleAnswer)
        {
            Question question = new Question();
            question.Id = id;
            question.Text = text;
            question.CorrectArgument = correctArgument;
            question.SubcategoryId = subcategoryId;
            question.MultipleAnswer = multipleAnswer;
            return question;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Text
        {
            get
            {
                return _Text;
            }
            set
            {
                OnTextChanging(value);
                ReportPropertyChanging("Text");
                _Text = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Text");
                OnTextChanged();
            }
        }
        private global::System.String _Text;
        partial void OnTextChanging(global::System.String value);
        partial void OnTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CorrectArgument
        {
            get
            {
                return _CorrectArgument;
            }
            set
            {
                OnCorrectArgumentChanging(value);
                ReportPropertyChanging("CorrectArgument");
                _CorrectArgument = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CorrectArgument");
                OnCorrectArgumentChanged();
            }
        }
        private global::System.String _CorrectArgument;
        partial void OnCorrectArgumentChanging(global::System.String value);
        partial void OnCorrectArgumentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid SubcategoryId
        {
            get
            {
                return _SubcategoryId;
            }
            set
            {
                OnSubcategoryIdChanging(value);
                ReportPropertyChanging("SubcategoryId");
                _SubcategoryId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SubcategoryId");
                OnSubcategoryIdChanged();
            }
        }
        private global::System.Guid _SubcategoryId;
        partial void OnSubcategoryIdChanging(global::System.Guid value);
        partial void OnSubcategoryIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean MultipleAnswer
        {
            get
            {
                return _MultipleAnswer;
            }
            set
            {
                OnMultipleAnswerChanging(value);
                ReportPropertyChanging("MultipleAnswer");
                _MultipleAnswer = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MultipleAnswer");
                OnMultipleAnswerChanged();
            }
        }
        private global::System.Boolean _MultipleAnswer;
        partial void OnMultipleAnswerChanging(global::System.Boolean value);
        partial void OnMultipleAnswerChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KTModel", "fk_Answers_Questionid", "Answer")]
        public EntityCollection<Answer> Answers
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Answer>("KTModel.fk_Answers_Questionid", "Answer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Answer>("KTModel.fk_Answers_Questionid", "Answer", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KTModel", "fk_GeneratedQuestions_QuestionId", "GeneratedQuestion")]
        public EntityCollection<GeneratedQuestion> GeneratedQuestions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<GeneratedQuestion>("KTModel.fk_GeneratedQuestions_QuestionId", "GeneratedQuestion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<GeneratedQuestion>("KTModel.fk_GeneratedQuestions_QuestionId", "GeneratedQuestion", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KTModel", "fk_Questions_SubcategoryId", "Subcategory")]
        public Subcategory Subcategory
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Subcategory>("KTModel.fk_Questions_SubcategoryId", "Subcategory").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Subcategory>("KTModel.fk_Questions_SubcategoryId", "Subcategory").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Subcategory> SubcategoryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Subcategory>("KTModel.fk_Questions_SubcategoryId", "Subcategory");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Subcategory>("KTModel.fk_Questions_SubcategoryId", "Subcategory", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KTModel", Name="Subcategory")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Subcategory : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Subcategory object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="categoryId">Initial value of the CategoryId property.</param>
        public static Subcategory CreateSubcategory(global::System.Guid id, global::System.String name, global::System.Guid categoryId)
        {
            Subcategory subcategory = new Subcategory();
            subcategory.Id = id;
            subcategory.Name = name;
            subcategory.CategoryId = categoryId;
            return subcategory;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid CategoryId
        {
            get
            {
                return _CategoryId;
            }
            set
            {
                OnCategoryIdChanging(value);
                ReportPropertyChanging("CategoryId");
                _CategoryId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CategoryId");
                OnCategoryIdChanged();
            }
        }
        private global::System.Guid _CategoryId;
        partial void OnCategoryIdChanging(global::System.Guid value);
        partial void OnCategoryIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KTModel", "fk_Questions_SubcategoryId", "Question")]
        public EntityCollection<Question> Questions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Question>("KTModel.fk_Questions_SubcategoryId", "Question");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Question>("KTModel.fk_Questions_SubcategoryId", "Question", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KTModel", "fk_tests_SubcategoryId", "Test")]
        public EntityCollection<Test> Tests
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Test>("KTModel.fk_tests_SubcategoryId", "Test");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Test>("KTModel.fk_tests_SubcategoryId", "Test", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KTModel", Name="Test")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Test : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Test object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="startDate">Initial value of the StartDate property.</param>
        /// <param name="minutesDuration">Initial value of the MinutesDuration property.</param>
        /// <param name="subcategoryId">Initial value of the SubcategoryId property.</param>
        /// <param name="endDate">Initial value of the EndDate property.</param>
        public static Test CreateTest(global::System.Guid id, global::System.String name, global::System.DateTime startDate, global::System.Int32 minutesDuration, global::System.Guid subcategoryId, global::System.DateTime endDate)
        {
            Test test = new Test();
            test.Id = id;
            test.Name = name;
            test.StartDate = startDate;
            test.MinutesDuration = minutesDuration;
            test.SubcategoryId = subcategoryId;
            test.EndDate = endDate;
            return test;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime StartDate
        {
            get
            {
                return _StartDate;
            }
            set
            {
                OnStartDateChanging(value);
                ReportPropertyChanging("StartDate");
                _StartDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartDate");
                OnStartDateChanged();
            }
        }
        private global::System.DateTime _StartDate;
        partial void OnStartDateChanging(global::System.DateTime value);
        partial void OnStartDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MinutesDuration
        {
            get
            {
                return _MinutesDuration;
            }
            set
            {
                OnMinutesDurationChanging(value);
                ReportPropertyChanging("MinutesDuration");
                _MinutesDuration = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MinutesDuration");
                OnMinutesDurationChanged();
            }
        }
        private global::System.Int32 _MinutesDuration;
        partial void OnMinutesDurationChanging(global::System.Int32 value);
        partial void OnMinutesDurationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid SubcategoryId
        {
            get
            {
                return _SubcategoryId;
            }
            set
            {
                OnSubcategoryIdChanging(value);
                ReportPropertyChanging("SubcategoryId");
                _SubcategoryId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SubcategoryId");
                OnSubcategoryIdChanged();
            }
        }
        private global::System.Guid _SubcategoryId;
        partial void OnSubcategoryIdChanging(global::System.Guid value);
        partial void OnSubcategoryIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime EndDate
        {
            get
            {
                return _EndDate;
            }
            set
            {
                OnEndDateChanging(value);
                ReportPropertyChanging("EndDate");
                _EndDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EndDate");
                OnEndDateChanged();
            }
        }
        private global::System.DateTime _EndDate;
        partial void OnEndDateChanging(global::System.DateTime value);
        partial void OnEndDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> QuestionCount
        {
            get
            {
                return _QuestionCount;
            }
            set
            {
                OnQuestionCountChanging(value);
                ReportPropertyChanging("QuestionCount");
                _QuestionCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("QuestionCount");
                OnQuestionCountChanged();
            }
        }
        private Nullable<global::System.Int32> _QuestionCount;
        partial void OnQuestionCountChanging(Nullable<global::System.Int32> value);
        partial void OnQuestionCountChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KTModel", "fk_GeneratedTests_TestId", "GeneratedTest")]
        public EntityCollection<GeneratedTest> GeneratedTests
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<GeneratedTest>("KTModel.fk_GeneratedTests_TestId", "GeneratedTest");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<GeneratedTest>("KTModel.fk_GeneratedTests_TestId", "GeneratedTest", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KTModel", "fk_tests_SubcategoryId", "Subcategory")]
        public Subcategory Subcategory
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Subcategory>("KTModel.fk_tests_SubcategoryId", "Subcategory").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Subcategory>("KTModel.fk_tests_SubcategoryId", "Subcategory").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Subcategory> SubcategoryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Subcategory>("KTModel.fk_tests_SubcategoryId", "Subcategory");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Subcategory>("KTModel.fk_tests_SubcategoryId", "Subcategory", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KTModel", "Subscriptions", "User")]
        public EntityCollection<User> Users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<User>("KTModel.Subscriptions", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<User>("KTModel.Subscriptions", "User", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KTModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="username">Initial value of the Username property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        /// <param name="passwordHint">Initial value of the PasswordHint property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="firstName">Initial value of the FirstName property.</param>
        /// <param name="lastName">Initial value of the LastName property.</param>
        /// <param name="isAdmin">Initial value of the IsAdmin property.</param>
        public static User CreateUser(global::System.String username, global::System.String password, global::System.String passwordHint, global::System.String email, global::System.String firstName, global::System.String lastName, global::System.Boolean isAdmin)
        {
            User user = new User();
            user.Username = username;
            user.Password = password;
            user.PasswordHint = passwordHint;
            user.Email = email;
            user.FirstName = firstName;
            user.LastName = lastName;
            user.IsAdmin = isAdmin;
            return user;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Username
        {
            get
            {
                return _Username;
            }
            set
            {
                if (_Username != value)
                {
                    OnUsernameChanging(value);
                    ReportPropertyChanging("Username");
                    _Username = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Username");
                    OnUsernameChanged();
                }
            }
        }
        private global::System.String _Username;
        partial void OnUsernameChanging(global::System.String value);
        partial void OnUsernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PasswordHint
        {
            get
            {
                return _PasswordHint;
            }
            set
            {
                OnPasswordHintChanging(value);
                ReportPropertyChanging("PasswordHint");
                _PasswordHint = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PasswordHint");
                OnPasswordHintChanged();
            }
        }
        private global::System.String _PasswordHint;
        partial void OnPasswordHintChanging(global::System.String value);
        partial void OnPasswordHintChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsAdmin
        {
            get
            {
                return _IsAdmin;
            }
            set
            {
                OnIsAdminChanging(value);
                ReportPropertyChanging("IsAdmin");
                _IsAdmin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsAdmin");
                OnIsAdminChanged();
            }
        }
        private global::System.Boolean _IsAdmin;
        partial void OnIsAdminChanging(global::System.Boolean value);
        partial void OnIsAdminChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KTModel", "fk_Categories_users", "Category")]
        public EntityCollection<Category> Categories
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Category>("KTModel.fk_Categories_users", "Category");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Category>("KTModel.fk_Categories_users", "Category", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KTModel", "fk_GeneratedTests_Username", "GeneratedTest")]
        public EntityCollection<GeneratedTest> GeneratedTests
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<GeneratedTest>("KTModel.fk_GeneratedTests_Username", "GeneratedTest");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<GeneratedTest>("KTModel.fk_GeneratedTests_Username", "GeneratedTest", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KTModel", "Subscriptions", "Test")]
        public EntityCollection<Test> Tests
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Test>("KTModel.Subscriptions", "Test");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Test>("KTModel.Subscriptions", "Test", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
